accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('<int:user_pk>/', views.detail, name='detail'),
    path('logout/', views.logout, name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('reviews/', include('reviews.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/delete/', views.delete, name='delete'),
    path('<int:review_pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:review_pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

reviews/models.py
from django.db import models
from django.conf import settings

class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    image = models.ImageField(upload_to='articles/', blank=True)
    movie_name = models.CharField(max_length=80)
    grade_choices = (
        (1, '★'),
        (2, '★★'),
        (3, '★★★'),
        (4, '★★★★'),
        (5, '★★★★★'),
    )
    grade = models.IntegerField(choices=grade_choices)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.TextField(max_length=80)
    created_at = models.DateTimeField(auto_now_add=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'email', 'first_name', 'last_name',)

reviews/forms.py
from django import forms
from .models import Review, Comment

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'movie_name', 'grade', 'content', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]
        widgets = {
            'content': forms.Textarea(attrs={'rows': 2})
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('reviews:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)

def detail(request, user_pk):
    user = get_user_model().objects.get(pk=user_pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

config/views.py
from django.shortcuts import render

def index(request):

    return render(request, 'index.html')

reviews/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ReviewForm, CommentForm
from .models import Review, Comment
from django.contrib import messages

@login_required
def create(request):
    if request.method == 'POST':
        review_form = ReviewForm(request.POST, request.FILES)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect('reviews:index')
    else:
        review_form = ReviewForm()
    context = {
        'review_form': review_form
    }
    return render(request, 'reviews/form.html', context=context)
    
def index(request):
    reviews = Review.objects.order_by('-pk')
    context = {
        'reviews': reviews
    }
    return render(request, 'reviews/index.html', context)

def detail(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comment_form = CommentForm()
    comments = review.comment_set.all()
    context = {
        'review': review,
        'comment_form': comment_form,
        'comments': comments
    }
    return render(request, 'reviews/detail.html', context)

@login_required
def update(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    if request.user == review.user: 
        if request.method == 'POST':
            review_form = ReviewForm(request.POST, request.FILES, instance=review)
            if review_form.is_valid():
                review_form.save()
                return redirect('reviews:detail', review.pk)
        else:
            review_form = ReviewForm(instance=review)
        context = {
            'review_form': review_form
        }
        return render(request, 'reviews/form.html', context)
    else:
        messages.warning(request, '작성자만 수정할 수 있습니다.')
        return redirect('reviews:detail', review.pk)

@login_required
def delete(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    review.delete()
    return redirect('reviews:index')

@login_required
def comment_create(request, review_pk):
    review = Review.objects.get(pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
    return redirect('reviews:detail', review.pk)

@login_required
def comment_delete(request, review_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('articles:detail', review_pk)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="box w-100">
    <div class="box yellow shadow rounded-4 w-75 position-relative">
      <div class="position-absolute top-0 start-50 translate-middle">
        <h1 class="display-2 text-warning txt-shadow">{{ user }}'S INFO</h1>
      </div>
      <div class="box w-100 pt-5 pb-3 px-3">
        <dl class="row">
          <dt class="col-sm-3 text-center">username</dt>
          <dd class="col-sm-9">{{ user.username }}</dd>
          <dt class="col-sm-3 text-center">date_joined</dt>
          <dd class="col-sm-9">{{ user.date_joined }}</dd>
          <dt class="col-sm-3 text-center">email</dt>
          <dd class="col-sm-9">{{ user.email }}</dd>
          <dt class="col-sm-3 text-center">last_name</dt>
          <dd class="col-sm-9">{{ user.last_name }}</dd>
          <dt class="col-sm-3 text-center">first_name</dt>
          <dd class="col-sm-9">{{ user.first_name }}</dd>
        </dl>
      </div>
      <div class="w-100 left px-3">
        {% if request.user.is_authenticated %}
          <a class="red click rounded-pill m-1 px-3" href="{% url 'accounts:logout' %}">LOGOUT</a>
        {% else %}
          <a class="green click rounded-pill m-1 px-3" href="{% url 'accounts:login' %}">LOGIN</a>
        {% endif %}
        <a class="blue click rounded-pill m-1 px-3" href="{% url 'reviews:index' %}">HOME</a>
      </div>
    </div>
    <hr>
    <div class="row w-75">
      <div class="col-6">
        <p class="text-muted text-center">
          {{ user.review_set.count }}
          REVIEWS
        </p>
        {% for review in user.review_set.all %}
          <div class="yellow shadow rounded-4 w-100 my-1">
            <div class="row p-1 w-100">
              <div class="col-2 py-1">
                <p class="my-1 mx-3">{{ review.pk }}</p>
              </div>
              <div class="col-10 py-2">
                <a class="text-dark my-1" href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <div class="col-6">
        <p class="text-muted text-center">
          {{ user.comment_set.count }}
          COMMENTS
        </p>
        {% for comment in user.comment_set.all %}
          <div class="yellow shadow rounded-4 w-100 my-1">
            <div class="row p-1 w-100">
              <div class="col-2 py-1">
                <p class="my-1 mx-3">{{ forloop.counter }}</p>
              </div>
              <div class="col-10 py-2">
                <a class="text-dark my-1" href="{% url 'reviews:detail' comment.review.pk %}">{{ comment.content }}</a>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="box yellow shadow rounded-4 w-50 position-relative">
    <div class="position-absolute top-0 start-50 translate-middle">
      <h1 class="display-2 text-warning txt-shadow">LOGIN</h1>
    </div>
    <div class="box w-100 pt-5 pb-3 px-3">
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="left">
          <input class="blue click rounded-pill my-1 px-3" type="submit" value="OK">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="box yellow shadow rounded-4 w-50 position-relative">
    <div class="position-absolute top-0 start-50 translate-middle">
      <h1 class="display-2 text-warning txt-shadow">SIGNUP</h1>
    </div>
    <div class="box w-100 pt-5 pb-3 px-3">
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="left">
          <input class="green click rounded-pill my-1 px-3" type="submit" value="OK">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

config/templates/base.html
{% load django_bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
  </head>

  <body>
    {% block content %}{% endblock %}
  </body>

</html>

config/templates/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="box yellow shadow rounded-4 w-50 position-relative">
    <div class="position-absolute top-0 start-50 translate-middle">
      <h1 class="display-2 text-warning txt-shadow">START</h1>
    </div>
    <div class="box w-50 pt-5 pb-3">
      <a class="red click rounded-pill w-100 my-1" href="{% url 'reviews:index' %}">HOME</a>
      <a class="green click rounded-pill w-100 my-1" href="{% url 'accounts:signup' %}">SIGNUP</a>
      <a class="blue click rounded-pill w-100 my-1" href="{% url 'accounts:login' %}">LOGIN</a>
    </div>
  </div>
{% endblock %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="box w-100">
    <div class="box yellow shadow rounded-4 w-75 position-relative">
      <div class="position-absolute top-0 start-50 translate-middle">
        <h1 class="display-2 text-warning txt-shadow">NO.{{ review.pk }}</h1>
      </div>
      <div class="box w-100 pt-5 pb-3 px-3">
        <div class="row">
          <div class="col-5">
            <img class="w-100" src="{{ review.image.url }}" alt="{{ review.image }}">
          </div>
          <div class="col-7 d-flex align-items-center">
            <dl class="row">
              <dt class=" col-sm-3 text-center">title</dt>
              <dd class="col-sm-9">{{ review.title }}</dd>
              <dt class=" col-sm-3 text-center">movie_name</dt>
              <dd class="col-sm-9">{{ review.movie_name }}</dd>
              <dt class=" col-sm-3 text-center">grade</dt>
              <dd class="col-sm-9">
                {{ review.get_grade_display }}
                {{ review.grade }}
              </dd>
              <dt class="col-sm-3 text-center">content</dt>
              <dd class="col-sm-9">{{ review.content }}</dd>
              <dt class=" col-sm-3 text-center">username</dt>
              <dd class="col-sm-9">
                <a class="text-black" href="{% url 'accounts:detail' review.user.pk %}">
                  {{ review.user.username }}
                </a>
              </dd>
              <dt class="col-sm-3 text-center">created_at</dt>
              <dd class="col-sm-9">{{ review.created_at | date:"Y-m-d" }}</dd>
              <dt class="col-sm-3 text-center">updated_at</dt>
              <dd class="col-sm-9">{{ review.updated_at | date:"Y-m-d" }}</dd>
            </dl>
          </div>
        </div>
      </div>
      <div class="w-100 left px-3">
        {% if request.user.is_authenticated %}
          {% if request.user == review.user %}
            <a class="blue click rounded-pill m-1 px-3" href="{% url 'reviews:update' review.pk %}">UPDATE</a>
            <a class="red click rounded-pill m-1 px-3" href="{% url 'reviews:delete' review.pk %}">DELETE</a>
          {% endif %}
        {% endif %}
      </div>
    </div>
    <hr>
    <form class="w-75" action="{% url 'reviews:comment_create' review.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      <div class="left">
        <input class="green click rounded-pill my-1 px-3" type="submit" value="OK">
      </div>
    </form>
    <hr>
    <p class="text-muted text-center">
      {{ comments|length }}
      COMMENTS
    </p>
    {% for comment in comments %}
      <div class="yellow shadow rounded-4 w-75 my-1">
        <div class="row p-1 w-100">
          <div class="col-2 py-2">
            <p class="my-1 mx-3">{{ comment.user.username }}</p>
          </div>
          <div class="col-9 py-2">
            <p class="my-1 mx-3">{{ comment.content }}</p>
          </div>
          {% if request.user.is_authenticated %}
            {% if request.user == comment.user %}
              <div class="col-1 py-1 left">
                <a class="red click rounded-pill px-3" href="{% url 'reviews:comment_delete' review.pk comment.pk %}">DELETE</a>
              </div>
            {% endif %}
          {% endif %}
        </div>
      </div>
      {% empty %}
      <p class="text-muted text-center">0 COMMENTS</p>
    {% endfor %}
  </div>
{% endblock %}

reviews/templates/reviews/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="box yellow shadow rounded-4 w-50 position-relative">
    <div class="w-100 position-absolute top-0 start-50 translate-middle">
      <h1 class="display-2 text-warning txt-shadow text-center">
        {% if request.resolver_match.url_name == 'create' %}
          NEW REVIEW
        {% else %}
          EDIT REVIEW
        {% endif %}
      </h1>
    </div>
    <div class="box w-100 pt-5 pb-3 px-3">
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form review_form %}
        <div class="left">
          <input class="green click rounded-pill my-1 px-3" type="submit" value="OK">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="box w-100 m-3 p-5">
    <h1 class="display-2 text-warning txt-shadow">REVIEWS</h1>
    <div class="w-100 left px-3">
      {% if request.user.is_authenticated %}
        <a class="red click rounded-pill m-1 px-3" href="{% url 'accounts:logout' %}">LOGOUT</a>
        <a class="green click rounded-pill m-1 px-3" href="{% url 'reviews:create' %}">NEW REVIEW</a>
      {% else %}
        <a class="green click rounded-pill my-1 px-3" href="{% url 'accounts:signup' %}">SIGNUP</a>
        <a class="blue click rounded-pill my-1 px-3" href="{% url 'accounts:login' %}">LOGIN</a>
      {% endif %}
    </div>
    <div class="row w-100">
      {% for review in reviews %}
        <div class="col-4">
          <div class="box yellow shadow rounded-4 position-relative">
            <div class="position-absolute top-0 start-50 translate-middle">
              <h1 class="display-4 text-warning txt-shadow">NO.{{ review.pk }}</h1>
            </div>
            <div class="box w-100 pt-4 pb-3 px-3">
              <img src="{{ review.image.url }}" class="card-img-top" alt="...">
              <a class="text-dark fs-4 fw-bold mx-0" href="{% url 'reviews:detail' review.pk %}">{{ review.title }}</a>
              <p class="m-0 w-100 text-center">
                {{ review.movie_name }}
                |
                {{ review.get_grade_display }}
              </p>
              <p class="m-0 w-100 text-end">
                <a href="{% url 'accounts:detail' review.user.pk %}">
                  {{ review.user.username }}
                </a>
                |
                {{ review.created_at | date:"Y-m-d" }}
              </p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}